### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by fabriziotappero** [ortizdaniel/microflow#14]
On linux mint does not seem to work

fabrizio@fab-linux-samsung ~/Downloads $ java -jar Microflow-1.5.0.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/daniel/microflow/MicroflowApplication : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:443)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:65)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:349)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:348)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
fabrizio@fab-linux-samsung ~/Downloads $

**Comment by ortizdaniel** [comment]
Please try updating to Java 8 build 201.

**Comment by fabriziotappero** [comment]
Fixed updating java with:
sudo add-apt-repository ppa:webupd8team/java
sudo apt update; sudo apt install oracle-java8-installer

**Comment by ortizdaniel** [comment]
Perfect!

**Comment by fabriziotappero** [comment]
Thanks a lot Daniel.

cheers
Fabrizio
